### ISSUE TITLE
mint会报错

### ISSUE THREAD

**Issue by CosmosOutman** [danieleth2/atomicals-js#1]
Initializing worker: 9
Initializing worker: 10
Waiting for workers to complete...
got one finalCopyData:undefined
Solution found, try composing the transaction...
node:internal/event_target:1084
  process.nextTick(() => { throw err; });
                           ^

TypeError: Cannot read properties of undefined (reading 'byteLength')
    at chunkBuffer (F:\atom\2\dist\utils\file-utils.js:132:24)
    at appendMintUpdateRevealScript (F:\atom\2\dist\commands\command-helpers.js:516:49)
    at prepareCommitRevealConfig (F:\atom\2\dist\commands\command-helpers.js:142:67)
    at Worker.<anonymous> (F:\atom\2\dist\utils\atomical-operation-builder.js:511:99)
    at Worker.emit (node:events:515:28)
    at MessagePort.<anonymous> (node:internal/worker:263:53)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:810:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)

Node.js v21.1.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by CosmosOutman** [comment]
> Initializing worker: 9 Initializing worker: 10 Waiting for workers to complete... got one finalCopyData:undefined Solution found, try composing the transaction... node:internal/event_target:1084 process.nextTick(() => { throw err; }); ^
> 
> TypeError: Cannot read properties of undefined (reading 'byteLength') at chunkBuffer (F:\atom\2\dist\utils\file-utils.js:132:24) at appendMintUpdateRevealScript (F:\atom\2\dist\commands\command-helpers.js:516:49) at prepareCommitRevealConfig (F:\atom\2\dist\commands\command-helpers.js:142:67) at Worker. (F:\atom\2\dist\utils\atomical-operation-builder.js:511:99) at Worker.emit (node:events:515:28) at MessagePort. (node:internal/worker:263:53) at [nodejs.internal.kHybridDispatch] (node:internal/event_target:810:20) at exports.emitMessage (node:internal/per_context/messageport:23:28)
> 
> Node.js v21.1.0 error Command failed with exit code 1. info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
